name: CI
on: [push, pull_request]

jobs:
    unit-test-job:
        name: run unit-test job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${OWNER,,}
                  password: ${{ secrets.GHCR_PAT }}
              env:
                  OWNER: ${{ github.repository_owner }}
            - name: Set up Docker
              run: |
                  docker pull ghcr.io/kanaiyuma-aist/test:latest
                  docker-compose up -d
              # run: |
              #     docker pull ghcr.io/${OWNER,,}/python-test-env:latest
              #     docker-compose up -d
              # env:
              #     OWNER: ${{ github.repository_owner }}
            - name: test
              run: docker run -it -d --name test ghcr.io/kanaiyuma-aist/test:latest

# jobs:
#   build-and-test:
#     # runs-on: ${{ matrix.os }}
#     runs-on: ubuntu-22.04
#     # runs-on:
#     #   group: ubuntu-runners
#     #   labels: ubuntu-20.04-16core
#     # container:
#     #   image: ghcr.io/kanaiyuma-aist/test:latest
#     strategy:
#       matrix:
#         #os: [ubuntu-latest, macos-latest, windows-latest]
#         os: [ubuntu-latest]
#         #python-version: ['3.8', '3.9', '3.10']
#         python-version: ['3.8']
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#     #   - name: Set Up ${{ matrix.python-version }}
#     #     uses: actions/setup-python@v4
#     #     with:
#     #       python-version: ${{ matrix.python-version }}
#     #       cache: 'pip'

#     #   - name: Install Software
#     #     run: |
#     #       python -m pip install --upgrade pip
#     #       pip install -r requirements_local.txt
#     #       pip freeze --all

#     #   - name: Supplemental Test
#     #     run: |
#     #       pytest -v tests/supplements/optuna_test.py
