name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest]
        #python-version: ['3.8', '3.9', '3.10']
        python-version: ['3.8']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          # cache: 'pip'

      - name: Install Software
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
          python setup.py install

      - name: Supplemental Test
        run: |
          pytest -v tests/supplements/optuna_test.py
